env = Environment()
env.Append(CCFLAGS=['-g'])
env.Append(CXXFLAGS=['-std=c++11'])

tlib = env.SharedLibrary('trickle', ['trickle.c', 'rand.c'])
container = env.Program('container', ['container.cpp'])
